// script.js - small site interactions: mobile menu and carousel touch handling
document.addEventListener('DOMContentLoaded', () => {
    const hamburger = document.querySelector('.hamburger');
    const nav = document.getElementById('siteNav');

    if (hamburger && nav) {
        hamburger.addEventListener('click', () => {
            const expanded = hamburger.getAttribute('aria-expanded') === 'true';
            hamburger.setAttribute('aria-expanded', String(!expanded));
            nav.classList.toggle('show');
        });

        // Close menu when a nav link is clicked
        nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => {
            if (nav.classList.contains('show')) {
                nav.classList.remove('show');
                hamburger.setAttribute('aria-expanded', 'false');
            }
        }));
    }

    // Carousel: pause animation while user touches/presses
    const carousel = document.querySelector('.carousel-inner');
    if (carousel) {
        const pause = () => { carousel.style.animationPlayState = 'paused'; };
        const resume = () => { carousel.style.animationPlayState = 'running'; };
        carousel.addEventListener('mouseenter', pause);
        carousel.addEventListener('mouseleave', resume);
        carousel.addEventListener('touchstart', pause, { passive: true });
        carousel.addEventListener('touchend', resume);
    }

    // Testimonials auto-rotate
    const testimonials = document.querySelectorAll('.testimonial');
    if (testimonials.length) {
        let ti = 0;
        setInterval(() => {
            testimonials[ti].classList.remove('active');
            ti = (ti + 1) % testimonials.length;
            testimonials[ti].classList.add('active');
        }, 6000);
    }

    // FAQ accordion
    document.querySelectorAll('.faq-q').forEach(btn => {
        btn.addEventListener('click', () => {
            const a = btn.nextElementSibling;
            a.classList.toggle('open');
        });
    });

    // Smooth scrolling for anchor links (redundant but helpful)
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            const href = this.getAttribute('href');
            if (href.length > 1) {
                e.preventDefault();
                document.querySelector(href).scrollIntoView({ behavior: 'smooth' });
            }
        });
    });

    // Reveal .card elements when they enter the viewport (works across all pages)
    const cardsToReveal = document.querySelectorAll('.card');
    if (cardsToReveal.length) {
        const cardObserver = new IntersectionObserver(entries => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('active');
                    cardObserver.unobserve(entry.target);
                }
            });
        }, { threshold: 0.12 });
        cardsToReveal.forEach(c => cardObserver.observe(c));
    }

    // About page top banner rotation (fade) - uses elements with class .banner-slide
    (function initAboutBanner(){
        const banner = document.getElementById('aboutBanner');
        if (!banner) return;
        const slides = Array.from(banner.querySelectorAll('.banner-slide'));
        if (!slides.length) return;
        let idx = 0;
        // ensure first slide active
        slides.forEach((s,i)=> s.classList.toggle('active', i===0));
        let timer = setInterval(next, 5000);
        function next(){
            slides[idx].classList.remove('active');
            slides[idx].setAttribute('aria-hidden','true');
            idx = (idx+1) % slides.length;
            slides[idx].classList.add('active');
            slides[idx].setAttribute('aria-hidden','false');
        }
        // pause on hover/touch
        banner.addEventListener('mouseenter', ()=> clearInterval(timer));
        banner.addEventListener('mouseleave', ()=> timer = setInterval(next,5000));
        banner.addEventListener('touchstart', ()=> clearInterval(timer), {passive:true});
        banner.addEventListener('touchend', ()=> timer = setInterval(next,5000));
    })();

    // Load images manifest (generated by generate_manifest.ps1) if present
        async function loadImagesManifest() {
            // Helper that creates an <img> element which first tries images/<name> then <name> then leaves the last-failed url
                function createImgWithLocalFallback(baseSrc, alt) {
                const img = document.createElement('img');
                img.loading = 'lazy';
                img.alt = alt || '';
                // if src looks like a remote URL, use it directly
                try {
                    const u = new URL(baseSrc);
                    img.src = baseSrc;
                    return img;
                } catch (e) {
                    // not an absolute URL, try images/<baseSrc> first
                }
                    let attempts;
                    if (baseSrc.startsWith('images/')) {
                        // try the images/ path first, then the bare filename
                        attempts = [baseSrc, baseSrc.replace(/^images\//, '')];
                    } else {
                        attempts = [`images/${baseSrc}`, baseSrc];
                    }
                let attempt = 0;
                img.onerror = function () {
                    attempt += 1;
                    if (attempt < attempts.length) {
                        img.src = attempts[attempt];
                    } else {
                        // all attempts failed; leave the last value
                        img.onerror = null;
                    }
                };
                // start with the first candidate
                img.src = attempts[0];
                return img;
            }

            try {
                // Try images/manifest.json first, then fall back to ./manifest.json at project root.
                let res;
                try { res = await fetch('images/manifest.json', {cache: 'no-store'}); } catch(e) { res = null; }
                if (!res || !res.ok) {
                    try { res = await fetch('./manifest.json', {cache: 'no-store'}); } catch(e) { res = null; }
                }
                if (!res || !res.ok) return;
                const manifest = await res.json();
                const features = manifest.features || [];
                const services = manifest.services || [];

                // Populate carousel
                const carouselInner = document.getElementById('carouselInner');
                if (carouselInner && features.length) {
                    carouselInner.innerHTML = '';
                    // create figure items with graceful fallbacks
                    features.forEach((src, i) => {
                        const fig = document.createElement('figure');
                        fig.style.borderRadius = '10px';
                        const img = createImgWithLocalFallback(src, `Feature image ${i+1}`);
                        img.style.display = 'block';
                        img.style.width = '100%';
                        img.style.height = '100%';
                        img.style.objectFit = 'cover';
                        const cap = document.createElement('figcaption');
                        cap.textContent = '';
                        fig.appendChild(img);
                        fig.appendChild(cap);
                        carouselInner.appendChild(fig);
                    });
                    // duplicate the set for seamless scroll
                    const clone = carouselInner.innerHTML;
                    carouselInner.innerHTML += clone;
                    // update og:image for better social preview when site is hosted
                    try {
                        const og = document.querySelector('meta[property="og:image"]');
                        if (og && features[0]) {
                            og.setAttribute('content', features[0]);
                        }
                    } catch (e) {}
                }

                // Replace feature card images if available (use fallback attempts)
                document.querySelectorAll('.feature-img').forEach((imgEl) => {
                    const idx = Number(imgEl.dataset.featureIndex || 0);
                    if (features[idx]) {
                        const newImg = createImgWithLocalFallback(features[idx]);
                        // copy all attributes from the original element (class, data-*, style, alt, etc.)
                        for (let i = 0; i < imgEl.attributes.length; i++) {
                            const attr = imgEl.attributes[i];
                            // Skip src because newImg.src is set by createImgWithLocalFallback
                            if (attr.name === 'src') continue;
                            try { newImg.setAttribute(attr.name, attr.value); } catch (e) {}
                        }
                        imgEl.replaceWith(newImg);
                    }
                });

                // Replace service images if available
                document.querySelectorAll('.service-img').forEach((imgEl) => {
                    const idx = Number(imgEl.dataset.serviceIndex || 0);
                    if (services[idx]) {
                        const newImg = createImgWithLocalFallback(services[idx]);
                        for (let i = 0; i < imgEl.attributes.length; i++) {
                            const attr = imgEl.attributes[i];
                            if (attr.name === 'src') continue;
                            try { newImg.setAttribute(attr.name, attr.value); } catch (e) {}
                        }
                        imgEl.replaceWith(newImg);
                    }
                });
            } catch (e) {
                // manifest not found or parse error — silently ignore and keep fallbacks
                // avoid spamming the console
            }
        }

        loadImagesManifest();
});

        // Modal & counters logic
        document.addEventListener('DOMContentLoaded', () => {
            const fab = document.getElementById('contactFab');
            const modal = document.getElementById('contactModal');
            const close = modal && modal.querySelector('.modal-close');
            const cancel = document.getElementById('modalCancel');
            function openModal() { if (!modal) return; modal.setAttribute('aria-hidden','false'); document.body.style.overflow='hidden'; }
            function closeModal() { if (!modal) return; modal.setAttribute('aria-hidden','true'); document.body.style.overflow=''; }
            if (fab) fab.addEventListener('click', openModal);
            if (close) close.addEventListener('click', closeModal);
            if (cancel) cancel.addEventListener('click', closeModal);

            // close modal on Escape
            document.addEventListener('keydown', (e) => { if (e.key === 'Escape') closeModal(); });

            // Animated counters when visible
            const counters = document.querySelectorAll('.stat-num');
            if (counters.length) {
                const obs = new IntersectionObserver(entries => {
                    entries.forEach(entry => {
                        if (!entry.isIntersecting) return;
                        const el = entry.target;
                        const target = Number(el.dataset.target || 0);
                        let current = 0;
                        const step = Math.max(1, Math.floor(target / 60));
                        const timer = setInterval(() => {
                            current += step;
                            if (current >= target) { el.textContent = target; clearInterval(timer); }
                            else el.textContent = current;
                        }, 16);
                        obs.unobserve(el);
                    });

                    
                }, { threshold: 0.4 });
                counters.forEach(c => obs.observe(c));
            }
        });

        // Contact form submission (AJAX) — try local API then fallback to mailto
        document.addEventListener('DOMContentLoaded', () => {
            const form = document.getElementById('contactForm');
            if (!form) return;
            form.addEventListener('submit', async (e) => {
                e.preventDefault();
                const data = new FormData(form);
                const payload = {};
                data.forEach((v, k) => payload[k] = v);
                const apiUrl = form.action || '/api/contact';
                try {
                    const res = await fetch(apiUrl, {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify(payload)
                    });
                    const json = await res.json().catch(()=>({}));
                    if (res.ok && json && json.ok) {
                        alert('Thanks — we received your message.');
                        const modal = document.getElementById('contactModal'); if (modal) modal.setAttribute('aria-hidden','true');
                        form.reset();
                        return;
                    }
                    // If server returned non-ok, fall through to fallback
                } catch (err) {
                    // network or CORS error — fall through to mailto fallback
                    console.debug('Contact API failed, falling back to mailto', err);
                }

                // Fallback: open user's email client with prefilled content
                const mailto = form.dataset.mailto || '';
                if (mailto) {
                    const subject = encodeURIComponent('Website contact — ' + (payload.name || '')); 
                    const body = encodeURIComponent((payload.message || '') + '\n\nFrom: ' + (payload.name || '') + ' <' + (payload.email || '') + '>');
                    window.location.href = `mailto:${mailto}?subject=${subject}&body=${body}`;
                } else {
                    alert('Unable to send message from this browser. Please try again later.');
                }
            });
        });